#!/usr/bin/env python3
"""Generate the matched pair of input scripts for one comparison run.

The two sides do not start in the same place and never will: the reference
boots to the 2002 title screen and reaches the scenario only after a click and
a stub of an opening movie, while our trace mode starts the scenario at tick
zero because the two title screens are different programs.  So a run is
described once, in *scenario* ticks, and written out twice - shifted by the
reference's lead-in, with the title click prepended to the reference's copy.

    make_pair.py <name> [--offset N] [--first N] [--period N] [--count N]
    make_pair.py <name> --recording FILE

--recording turns a recorded run (reference/record.sh) into the pair: our
copy is the recording itself, the reference's is every tick of it - repeat
ends included - shifted by the lead-in, after the title click.

Writes <name>-ours.txt and <name>-ref.txt next to this script, and prints the
offset to pass to th2-trace-diff.
"""
import argparse
import pathlib

# How long the reference takes to get from its first frame to the scenario's:
# the title fade-in, the menu until the click at tick 200, and the fade-out.
# Read straight off the reference's own state trace, which is the point of
# having one - `state.txt` names the running script per tick, and
# EV_0301MORNING first appears on tick 236 against our tick 1.  Both sides
# write their state line at the end of the tick, so the two are directly
# comparable; they were not while ours wrote at the top, and the half frame
# of skew showed up as a one-tick lag in whatever changed that frame.  Guessing it
# from the pixels gave 426, because the scenario spends its first two hundred
# ticks on a black screen and there is nothing to see until the first
# background fades in - every offset matches equally well on a black frame.
REFERENCE_LEAD_IN = 235

TITLE_CLICK = """\
# Reference lead-in: the 2002 title screen, which our side does not have.
# はじめから (start) sits at about y=403 in 800x600 client coordinates.
150 move 400 403
200 lclick 3
"""


def main():
    p = argparse.ArgumentParser()
    p.add_argument("name")
    p.add_argument("--offset", type=int, default=REFERENCE_LEAD_IN,
                   help="reference ticks before the scenario's first tick")
    p.add_argument("--first", type=int, default=30,
                   help="scenario tick of the first click")
    p.add_argument("--period", type=int, default=30,
                   help="scenario ticks between clicks")
    p.add_argument("--count", type=int, default=40)
    p.add_argument("--recording", type=pathlib.Path,
                   help="a script written by toheart2 --record")
    p.add_argument("--repeat", action="store_true",
                   help="one repeating click instead of --count of them, "
                        "plus the number key that answers a choice")
    args = p.parse_args()

    here = pathlib.Path(__file__).resolve().parent

    if args.recording:
        return from_recording(here, args)

    # Extra events in scenario ticks, one per line, same syntax as the script
    # itself.  This is where the map screen lives: it is answered by the
    # pointer standing on a destination's rect when a click lands, and those
    # rects are per-scenario - MapEventCharPos[pos] with (cx+20, cy-118,
    # 130, 118) around it - so there is no one position that answers every
    # map in the game.  Kept in a file rather than generated, because each
    # line is a fact about one scene that had to be found by running it.
    extra = []
    extra_file = here / f"{args.name}-extra.txt"
    if extra_file.exists():
        for line in extra_file.read_text().splitlines():
            body = line.split("#", 1)[0].strip()
            if not body:
                continue
            tick, rest = body.split(None, 1)
            extra.append((int(tick), rest))

    if args.repeat:
        # A route is hundreds of thousands of ticks, which as one line per
        # click overruns the reference shim's event table and makes every tick
        # scan every event.  One repeat costs neither.
        #
        # num1 every tick, not every period, and that is the whole reason it is
        # here.  AVG_ControlSelectWindow reads GameKey.num[] only once the
        # options have finished typing, and answers with whichever of the two
        # arrives first - the number key, or a click while the cursor happens
        # to be inside an option's rect.  Which of those wins would otherwise
        # depend on where the parked cursor landed relative to text that moves
        # with every choice in the game.  Pressing it every tick settles it:
        # the first frame a choice can be answered, option one answers it, the
        # same way on both sides.  Outside a choice the key is inert - nothing
        # else in the engine reads GameKey.num[].
        ours = ["# Scenario ticks.  Generated by make_pair.py - do not hand-edit.",
                "1 move 400 403",
                f"{args.first} every {args.period} lclick 3",
                f"{args.first} every 1 num1"]
        ours += [f"{t} {rest}" for t, rest in extra]
        (here / f"{args.name}-ours.txt").write_text("\n".join(ours) + "\n")

        ref = [TITLE_CLICK.rstrip(),
               f"# Scenario ticks, shifted by {args.offset}.",
               f"{args.first + args.offset} every {args.period} lclick 3",
               f"{args.first + args.offset} every 1 num1"]
        ref += [f"{t + args.offset} {rest}" for t, rest in extra]
        (here / f"{args.name}-ref.txt").write_text("\n".join(ref) + "\n")

        print(f"wrote {args.name}-ours.txt and {args.name}-ref.txt (repeating)")
        print(f"offset: pass --offset {args.offset} to th2-trace-diff "
              f"(ours -> ref)")
        return

    clicks = [args.first + i * args.period for i in range(args.count)]

    ours = ["# Scenario ticks.  Generated by make_pair.py - do not hand-edit.",
            "1 move 400 403"]
    ours += [f"{t} lclick 3" for t in clicks]
    (here / f"{args.name}-ours.txt").write_text("\n".join(ours) + "\n")

    ref = [TITLE_CLICK.rstrip(),
           f"# Scenario ticks, shifted by {args.offset}."]
    ref += [f"{t + args.offset} lclick 3" for t in clicks]
    (here / f"{args.name}-ref.txt").write_text("\n".join(ref) + "\n")

    print(f"wrote {args.name}-ours.txt and {args.name}-ref.txt")
    print(f"offset: pass --offset {args.offset} to th2-trace-diff "
          f"(ours -> ref)")
    print(f"ticks: ours 0..{clicks[-1] + args.period}, "
          f"ref {args.offset}..{clicks[-1] + args.period + args.offset}")


def shift_line(body, offset):
    """One script line with its tick and any `until` tick moved by offset."""
    words = body.split()
    words[0] = str(int(words[0]) + offset)
    for i, word in enumerate(words[:-1]):
        if word.lower() == "until":
            words[i + 1] = str(int(words[i + 1]) + offset)
    return " ".join(words)


def last_tick(lines):
    """Where a recording's input stops mattering: its end marker if it has
    one, else the end of its latest event."""
    end = 0
    for line in lines:
        if line.startswith("# End of recording at tick"):
            return int(line.rsplit(None, 1)[-1].rstrip("."))
        body = line.split("#", 1)[0].split()
        if not body:
            continue
        tick = int(body[0])
        hold = 1
        if len(body) >= 3 and body[1].lower() not in ("move", "every"):
            try:
                hold = int(body[2])
            except ValueError:
                pass
        end = max(end, tick + hold)
    return end


def from_recording(here, args):
    lines = args.recording.read_text().splitlines()
    ours = [f"# {args.name}: {args.recording.name}, as recorded - scenario ticks."]
    ref = [TITLE_CLICK.rstrip(),
           f"# {args.name}: {args.recording.name}, shifted by {args.offset}."]
    for line in lines:
        ours.append(line)
        body = line.split("#", 1)[0].strip()
        if body:
            ref.append(shift_line(body, args.offset))
    (here / f"{args.name}-ours.txt").write_text("\n".join(ours) + "\n")
    (here / f"{args.name}-ref.txt").write_text("\n".join(ref) + "\n")
    end = last_tick(lines)
    print(f"wrote {args.name}-ours.txt and {args.name}-ref.txt from "
          f"{args.recording}")
    print(f"offset: pass --offset {args.offset} to th2-trace-diff "
          f"(ours -> ref)")
    print(f"last tick: {end}  (TH2_LAST={end} for mediawalk.sh)")


if __name__ == "__main__":
    main()
